"""Product table modified

Revision ID: 96e3506f015d
Revises: fb0fd886e1cf
Create Date: 2025-10-03 03:18:40.687168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e3506f015d'
down_revision: Union[str, Sequence[str], None] = 'fb0fd886e1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=False))
    op.add_column('products', sa.Column('description', sa.String(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
